# Generated by Django 3.2.12 on 2024-03-10 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advantage', models.JSONField()),
                ('restrictions', models.JSONField()),
            ],
        ),
    ]
